### ISSUE TITLE
Add toolbar and postMessage functionality to host page

### ISSUE THREAD

**Issue by richdizz** [OfficeDev/PnP-WOPI#1]
It would be helpful for the sample to illustrate the ability to postMessage between the host page and the WOPI frame. Some simple toolbar commands would be good.

**Comment by hannesne** [comment]
Additionally, the fact that the frame fills the screen obfuscates the fact that the page is still located within the client's domain, and the Office is only in a part of the page. It would be good to put a header and footer in there with the sample site's logo to illustrate the two different domains, and how you can customize the chrome.
