### ISSUE TITLE
Ruby on rails implementation?

### ISSUE THREAD

**Issue by BKSpurgeon** [OfficeDev/PnP-WOPI#10]
hi folks

thank you for providing this online. I appreciate it.

is there are ruby on rails implementation example for this? That would be very helpful.

rgds

Ben

**Comment by rogsmith** [comment]
@suhasg did you ever find an ROR implementation?

**Comment by rogsmith** [comment]
@benkoshy did you ever find an RoR implementation?

**Comment by benkoshy** [comment]
I did not.  I forgot how i solved  the problem
