### ISSUE TITLE
Issue with office online

### ISSUE THREAD

**Issue by seemantmishra** [OfficeDev/PnP-WOPI#11]
Hi,

I downloaded the solution and configured it with my azure cloud details.
1. I hosted the solution in one app service in azure.
2. I registered that app service in Azure AD directory.
3. I created one Blob storage.
4. I created one Azure Cosmos DB as documentDB.
5. I updated all the entries required in web.config file with mine cloud entries.
6. I am not using any SSL certificate and hence removed its dependency from code also and using Http instead of https.

Now when i am trying to run my application, it is saving my document in Azure blob storage and cosmos db (documentDB) both successfully.
But when I am trying to view the uploaded document, it is giving me error such as, "file couldn't be found either renamed or removed" for .xlsx file.

I found their was a note in the description : 
"You cannot simply clone and run this sample locally. Integrating with Office Online requires that your host domain is white-listed by Microsoft. The first step to white-listing a domain is to join the Cloud Storage Provider Program detail HERE. "  Is this causing the issue?

Thanks in advance !! Please guide me to resolve the issue.

**Comment by seemantmishra** [comment]
![image](https://user-images.githubusercontent.com/33538140/32649346-d8e2cf5a-c61f-11e7-8e09-e71617521be6.png)

This is the error I am getting when trying to open!! Please suggest what else needs to be done or updated in solution to get the required outcome.

**Comment by sirespeaks** [comment]
Ever find any resolution to this issue.  I am experiencing the exact same problem.

**Comment by akorade** [comment]
I am facing similar issue. Any resolution?
