### ISSUE TITLE
error message after the upload of a file: Unable to get property 'id' of undefined or null reference

### ISSUE THREAD

**Issue by Abdelkrim** [OfficeDev/PnP-WOPI#7]
Any idea why I receive the following error message after having drag-and-dropped a ms office file? 

Unable to get property 'id' of undefined or null reference

![pnp-wopi-unable get property id](https://cloud.githubusercontent.com/assets/791663/18176196/eb76ba34-7074-11e6-9d98-418ce97efbe5.PNG)

**Comment by skudinov** [comment]
that's because adding file fails, /Home/Add handler returns {success: false} w/o any troubleshooting information. I can imagine it might be something wrong with DocumentDB/AzureBlob subscriptions. 
Hey, guys can you please take a look or remove links to deployed version?
